# Generated by Django 5.0.3 on 2024-04-20 12:37

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='AccountsUtilisateursGroups',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('utilisateurs_id', models.BigIntegerField()),
                ('group_id', models.IntegerField()),
            ],
            options={
                'db_table': 'accounts_utilisateurs_groups',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AccountsUtilisateursUserPermissions',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('utilisateurs_id', models.BigIntegerField()),
                ('permission_id', models.IntegerField()),
            ],
            options={
                'db_table': 'accounts_utilisateurs_user_permissions',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AccountsUtilisateurs',
            fields=[
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('password', models.CharField(max_length=128)),
                ('last_login', models.DateTimeField(blank=True, null=True)),
                ('username', models.CharField(max_length=150, unique=True)),
                ('first_name', models.CharField(max_length=150)),
                ('last_name', models.CharField(max_length=150)),
                ('email', models.EmailField(max_length=254)),
                ('is_staff', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now)),
                ('role', models.CharField(max_length=30)),
                ('gender', models.CharField(max_length=30)),
                ('groups', models.ManyToManyField(blank=True, related_name='accounts_utilisateurs', to='auth.group')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'db_table': 'accounts_utilisateurs',
            },
        ),
    ]
