# Generated by Django 5.0.3 on 2024-03-31 18:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CommandeFournisseur',
            fields=[
                ('id_commande_fournisseur', models.AutoField(primary_key=True, serialize=False)),
                ('date_commande', models.DateTimeField()),
                ('etat', models.CharField(max_length=8)),
            ],
            options={
                'db_table': 'commande_fournisseur',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Fournisseur',
            fields=[
                ('id_fournisseur', models.AutoField(primary_key=True, serialize=False)),
                ('nom', models.CharField(max_length=255)),
                ('adresse', models.TextField(blank=True, null=True)),
                ('email', models.CharField(max_length=255, unique=True)),
                ('telephone', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'fournisseur',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='LigneCommandeFournisseur',
            fields=[
                ('id_ligne_commande_fournisseur', models.AutoField(primary_key=True, serialize=False)),
                ('id_commande_fournisseur', models.IntegerField(blank=True, null=True)),
                ('id_produit', models.IntegerField(blank=True, null=True)),
                ('quantite_commandee', models.IntegerField()),
                ('prix_unitaire', models.DecimalField(decimal_places=2, max_digits=10)),
                ('etat', models.CharField(max_length=8)),
            ],
            options={
                'db_table': 'ligne_commande_fournisseur',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Utilisateurs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=255)),
                ('prenom', models.CharField(max_length=255)),
                ('email', models.CharField(max_length=255, unique=True)),
                ('mot_de_passe', models.CharField(max_length=255)),
                ('role', models.CharField(max_length=12)),
            ],
            options={
                'db_table': 'utilisateurs',
                'managed': False,
            },
        ),
    ]
