# Generated by Django 5.0.3 on 2024-04-24 14:18

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id_client', models.AutoField(primary_key=True, serialize=False)),
                ('nom', models.CharField(max_length=255)),
                ('prenom', models.CharField(max_length=255)),
                ('adresse', models.TextField(blank=True, null=True)),
                ('email', models.CharField(max_length=255, unique=True)),
                ('telephone', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'client',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Vente',
            fields=[
                ('id_vente', models.AutoField(primary_key=True, serialize=False)),
                ('date_vente', models.DateTimeField(default=django.utils.timezone.now)),
                ('quantite', models.IntegerField()),
                ('prix_unitaire', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
            options={
                'db_table': 'vente',
                'managed': False,
            },
        ),
    ]
